# Created with WinGet Automation using Komac v1.10.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: xanderfrangos.twinkletray
PackageVersion: 1.15.5
InstallerLocale: en-US
InstallerType: nullsoft
Scope: user
InstallModes:
- silent
UpgradeBehavior: install
ReleaseDate: 2024-07-24
Installers:
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/xanderfrangos/twinkle-tray/releases/download/v1.15.5/Twinkle.Tray.v1.15.5.exe
  InstallerSha256: BDBE08DE1624A0C484E1F626183F6EA56778E6DBFC4AE44A74E0422B0E114CAD
ManifestType: installer
ManifestVersion: 1.6.0
